"""empty message

Revision ID: cdef472802a1
Revises: 
Create Date: 2021-03-23 21:40:02.835857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdef472802a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_logout', sa.DateTime(), nullable=True),
    sa.Column('full_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrators_email'), 'administrators', ['email'], unique=True)
    op.create_index(op.f('ix_administrators_password'), 'administrators', ['password'], unique=False)
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('airport_country', sa.String(length=120), nullable=False),
    sa.Column('airport_city', sa.String(length=120), nullable=False),
    sa.Column('airport_name', sa.String(length=120), nullable=False),
    sa.Column('airport_iata_identifier', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_airport_city'), 'airports', ['airport_city'], unique=False)
    op.create_index(op.f('ix_airports_airport_iata_identifier'), 'airports', ['airport_iata_identifier'], unique=False)
    op.create_table('subscriptors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptors_email'), 'subscriptors', ['email'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('departure_origin', sa.Integer(), nullable=False),
    sa.Column('departure_destination', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('return_origin', sa.Integer(), nullable=False),
    sa.Column('return_destination', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('passenger_companion', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['administrators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('weight_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['administrators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weights')
    op.drop_table('trips')
    op.drop_index(op.f('ix_subscriptors_email'), table_name='subscriptors')
    op.drop_table('subscriptors')
    op.drop_index(op.f('ix_airports_airport_iata_identifier'), table_name='airports')
    op.drop_index(op.f('ix_airports_airport_city'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_administrators_password'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_email'), table_name='administrators')
    op.drop_table('administrators')
    # ### end Alembic commands ###
